// src/app/components/projects/projects.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css'],
})
export class ProjectsComponent implements OnInit {
  public repos: any[] = [];

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    // This should be in a service but we are only making one API call
    if (
      // Check if we have the repos local
      localStorage.getItem('repos') !== undefined &&
      localStorage.getItem('repos') !== null
    ) {
      // We have the repos local
      // Check how old the local version is
      let exp = Number(localStorage.getItem('repos_exp'));
      if (exp > Date.now()) {
        // Repos are less than 2 hours old
        this.repos = JSON.parse(localStorage.getItem('repos')!);
        return;
      }
      localStorage.removeItem('repos_exp');
      localStorage.removeItem('repos');
    }
    this.http
      .get<any>('https://api.github.com/users/rs401/repos', {
        observe: 'response',
      })
      .subscribe({
        next: (response) => {
          this.repos = response.body;
          // Sort repos by 'pushed_at'
          this.repos.sort((a, b) => (a['pushed_at'] > b['pushed_at'] ? -1 : 1));
        },
        complete: () => {
          // This is needed to avoid Github's API limits during live reloads on
          // save during development.
          localStorage.setItem('repos', JSON.stringify(this.repos));
          let date = Date.now();
          let exp = date + 2 * (60 * 60 * 1000);
          localStorage.setItem('repos_exp', String(exp));
          console.log('repos_exp: ' + localStorage.getItem('repos_exp'));
        },
      });
  }
}

<mat-card>
    <mat-card-header>
        <mat-card-title>Projects</mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <mat-grid-list cols="3" rowHeight="200px">
            <mat-grid-tile
                *ngFor="let repo of repos"
                colspan="1"
                rowspan="1"
            >
            <app-project style="height: 100%;width: 100%;" [theRepo]="repo"></app-project>
            <!--
                <mat-card>
                    {{ repo['name'] }}
                </mat-card>
            -->
            </mat-grid-tile>
        </mat-grid-list>
    </mat-card-content>
</mat-card>

// src/pages/Projects.tsx
import { FC, useState, useEffect } from "react";
import HttpService from "../services/HttpService";
import RootPage from "./root";

interface Repo {
    name: string,
}

const Projects: FC = () => {
  const [repos, setRepos] = useState<any[]>([]);
  const githubUrl: string = (process.env.REACT_APP_GITHUB_URL as string);

  useEffect(() => {
    if (
        // Check if we have the repos local
        localStorage.getItem('repos') !== undefined &&
        localStorage.getItem('repos') !== null
      ) {
        // We have the repos local
        // Check how old the local version is
        let exp = Number(localStorage.getItem('repos_exp'));
        if (exp > Date.now()) {
          // Repos are less than 2 hours old
          console.log("We have the repos locally, no need to bother GitHub's API.");
          
          setRepos(JSON.parse(localStorage.getItem('repos')!));
          return;
        }
        localStorage.removeItem('repos_exp');
        localStorage.removeItem('repos');
      }
    HttpService.get(githubUrl).then((res:any[]) => {
        res.sort((a, b) => (a['pushed_at'] > b['pushed_at'] ? -1 : 1));
        setRepos(res);
        localStorage.setItem('repos', JSON.stringify(res));
          let date = Date.now();
          let exp = date + 2 * (60 * 60 * 1000);
          localStorage.setItem('repos_exp', String(exp));
          console.log('repos_exp: ' + localStorage.getItem('repos_exp'));
    });
    
  }, [githubUrl]);
  
  return (
    <RootPage>
        {repos && repos.length !== 0 ? (
            <div>
            {repos.map((repo: any, index: Number, repos: any[]) => {
                return <div key={index as React.Key}>{repo.name}</div>;
            })}
            </div>
        ):(
            <>Loading...</>
        )}
    </RootPage>
  );
};

export default Projects;
